exp:
  entity: kliang-personal
  project: sweetdreams
  group: vqvae_lr
  run_name: ema + random restart

data:
  h5_path: data/breakout.h5
  seq_len: 1
  train_frac: 0.8
  val_frac: 0.1

train:
  seed: 0
  epochs: 100
  batch_size: 512
  num_workers: 4
  device: auto
  limit_train_batches:
  limit_val_batches:
  limit_test_batches:

optimizer:
  type: adam
  lr: 0.0001

scheduler:
  type: none

codebook:
  init:
    type: kmeans
    num_batches: 10
    num_iters: 20
    chunk_size: 65536
  ema:
    decay: 0.99
    eps: 1e-5
    restart_threshold: 1.0

model:
  in_out_channels: 1
  hidden_dim: 128
  latent_dim: 256
  num_embeddings: 128
  commitment_cost: 0.25
