exp:
  entity: kliang-personal
  project: sweetdreams
  group: vqvae
  run_name: vqvae

data:
  h5_path: data/breakout.h5
  seq_len: 1
  train_frac: 0.8
  val_frac: 0.1

train:
  seed: 0
  epochs: 50
  batch_size: 256
  num_workers: 4
  device: auto

optimizer:
  type: adam
  lr: 0.0001

scheduler:
  type: none
  t_max: ${train.epochs}
  eta_min: 0.0

loss:
  perceptual_weight: 0.1
  perceptual_net: vgg

model:
  in_out_channels: 1
  hidden_dim: 256
  latent_dim: 256
  codebook:
    num_embeddings: 512
    commitment_cost: 0.25
    init:
      type: kmeans
      num_batches: 10
      num_iters: 20
      chunk_size: 65536
    ema:
      decay: 0.99
      eps: 1e-5
      restart_threshold: 1.0
